steps:
  # 1. Build the container image using Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/backend-repo/nestjs-backend-taluithai:$COMMIT_SHA'
      - '.'

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/backend-repo/nestjs-backend-taluithai:$COMMIT_SHA'

  # 3. Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'taluithai-backend' # Name of your Cloud Run service
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/backend-repo/nestjs-backend-taluithai:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1' # Singapore region (ideal for Thailand latency)
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/backend-repo/nestjs-backend-taluithai:$COMMIT_SHA'
